# Generated by Django 6.0.4 on 2026-05-02 10:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChaiVerities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('image', models.ImageField(upload_to='chais/')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('Masala Chai', 'Masala Chai'), ('Ginger Chai', 'Ginger Chai'), ('Cardamom Chai', 'Cardamom Chai'), ('Tulsi Chai', 'Tulsi Chai'), ('Lemon Chai', 'Lemon Chai')], max_length=50)),
            ],
        ),
    ]
